/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // start animation!
  skycons.play();
var cityCode = [2306179,2306186,2306181,2306182,2306180,22695855,28752472,2306185,2296872,2301128,2306183,2306204,
2347346,2296315,2306206,2306189,2306198,2306187,2306190,22695856,28760735,28760734];

  function changeSkycons(day,code){
    if(code === "32" ||code === "34" ||code === "36"){
      skycons.set(day,Skycons.CLEAR_DAY)
    }    
    else if(code === "31" || code === "33"){
      skycons.set(day,Skycons.CLEAR_NIGHT)
    }
    else if(code === "28" ||code === "30"){
      skycons.set(day,Skycons.PARTLY_CLOUDY_DAY)
    } 
    else if(code === "27" ||code === "29"){
      skycons.set(day,Skycons.PARTLY_CLOUDY_NIGHT)
    }  
    else if(code === "26" ||code === "44"){
      skycons.set(day,Skycons.CLOUDY)
    } 
    else if(code === "3" ||code === "4" ||code === "9" ||code === "11" || code === "12" || 
      code === "37" || code === "38" || code === "39" || code === "40" || code === "45" || code === "47"){
      skycons.set(day,Skycons.RAIN)
    } 
    else if(code === "23" ||code === "24"){
      skycons.set(day,Skycons.WIND)
    }  
    else{
      skycons.set(day,Skycons.CLEAR_DAY)
    }
  }


/*
Get value from Bootstrap dropdown menu
*/


function changeWeather(w){
  $.getJSON("http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid="+w+"&format=json",function(data){ 
    var temp = Math.round((data.query.results.channel.item.condition.temp-32)*5/9);
    var text = data.query.results.channel.item.condition.text;
    var forecast = data.query.results.channel.item.forecast;
    var code = data.query.results.channel.item.condition.code;
    $(".temperature").append(temp);
    $(".condition").append(" : "+text);

    changeSkycons("today",code);

    $.each(forecast,function(key,value){
      if(key === 0){
        $(".date").append(value.date);
      }
      else if(key === 1 || key === 2 || key ===3){
      $(".forecastDate").append("<th>"+value.date+"</th>");
      $(".forecastTemp").append("<td>"+Math.round((value.low-32)*5/9)+" - "+Math.round((value.high-32)*5/9)+" &#8451</td>");
      changeSkycons("day"+key,value.code);
    }
    });
  });
}

$.each(cityCode, function(key,value){
  $.getJSON("http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid="+value+"&format=json",function(data){
    var cityTemp = Math.round((data.query.results.channel.item.condition.temp-32)*5/9)
    $("#city"+key).append(" "+cityTemp+" &#8451;");
});
});

changeWeather(2306179);

function clear(){ 
  $(".temperature").empty();
  $(".condition").empty("");
  $("<span>").addClass("date").appendTo(".condition");
  $(".forecastDate").empty();
  $(".forecastTemp").empty();
};

$('#dropdown li').on('click', function(){
    $("button").text($(this).text());
});


$("#city0").on("click",function(){
  clear();
  changeWeather(cityCode[0]);
  $("button").text("台北市")
});

 $("#city1").on("click",function(){
   clear();
   changeWeather(cityCode[1]);
   //$("button").text("新北市")
 });

$("#city2").on("click",function(){
  clear();
  changeWeather(cityCode[2]);
  $("button").text("台中市")
});

$("#city3").on("click",function(){
  clear();
  changeWeather(cityCode[3]);
  $("button").text("台南市")
});

$("#city4").on("click",function(){
  clear();
  changeWeather(cityCode[4]);
  $("button").text("高雄市")
});

$("#city5").on("click",function(){
  clear();
  changeWeather(cityCode[5]);
  $("button").text("基隆市")
});

$("#city6").on("click",function(){
  clear();
  changeWeather(cityCode[6]);
  $("button").text("桃園市")
});

$("#city7").on("click",function(){
  clear();
  changeWeather(cityCode[7]);
  $("button").text("新竹市")
});

$("#city8").on("click",function(){
  clear();
  changeWeather(cityCode[8]);
  $("button").text("新竹縣")
});

$("#city9").on("click",function(){
  clear();
  changeWeather(cityCode[9]);
  $("button").text("苗栗縣")
});

$("#city10").on("click",function(){
  clear();
  changeWeather(cityCode[10]);
  $("button").text("彰化縣")
});

$("#city11").on("click",function(){
  clear();
  changeWeather(cityCode[11]);
  $("button").text("南投縣")
});

$("#city12").on("click",function(){
  clear();
  changeWeather(cityCode[12]);
  $("button").text("雲林縣")
});

$("#city13").on("click",function(){
  clear();
  changeWeather(cityCode[13]);
  $("button").text("嘉義市")
});

$("#city14").on("click",function(){
  clear();
  changeWeather(cityCode[14]);
  $("button").text("嘉義縣")
});

$("#city15").on("click",function(){
  clear();
  changeWeather(cityCode[15]);
  $("button").text("屏東縣")
});

$("#city16").on("click",function(){
  clear();
  changeWeather(cityCode[16]);
  $("button").text("宜蘭縣")
});

$("#city17").on("click",function(){
  clear();
  changeWeather(cityCode[17]);
  $("button").text("花蓮縣")
});

$("#city18").on("click",function(){
  clear();
  changeWeather(cityCode[18]);
  $("button").text("台東縣")
});

$("#city19").on("click",function(){
  clear();
  changeWeather(cityCode[19]);
  $("button").text("澎湖縣")
});

$("#city20").on("click",function(){
  clear();
  changeWeather(cityCode[20]);
  $("button").text("金門縣")
});

$("#city21").on("click",function(){
  clear();
  changeWeather(cityCode[21]);
  $("button").text("連江縣")
});

